### ISSUE TITLE
Restructure Release Please Configuration

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/kotlin-sdk#52]
The Release Please configuration should be updated to use the root of the project. That will move the change log to the root of the project and allow RP to manage the versions listed on the readme.

**Comment by nicklasl** [comment]
I believe that this PR does that? https://github.com/open-feature/kotlin-sdk/pull/49
We just haven't shipped any release since.

**Comment by beeme1mr** [comment]
@nicklasl, yep, you're right. I noticed that after creating the issue 😄 

Thanks for taking care of that.
