### ISSUE TITLE
Provider status management

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/kotlin-sdk#62]
As mentioned in the [specification](https://openfeature.dev/specification/sections/providers#requirement-242) :

>  The provider MAY define a status field/accessor which indicates the readiness of the provider, with possible values `NOT_READY`, `READY`, `STALE`, or `ERROR`.
Providers without this field can be assumed to be ready immediately.
The diagram below illustrates the possible states and transitions of the status fields.

Currently, the SDK does not offer the providers does take care of anything to indicate the readiness of the provider.
I was wondering if it was on purpose?

**Comment by nicklasl** [comment]
@thomaspoignant take a look at the linked PR, was it something like this you had in mind?

**Comment by thomaspoignant** [comment]
@nicklasl sorry for the delay in the answer but yes this is what I had in mind.
