### ISSUE TITLE
Rename artifact android-sdk

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/kotlin-sdk#67]
The main goal of this repository is to build a client SDK for Android users.
For now, the artifact is called `Kotlin-sdk` that is compatible with Android only, this could be misleading because Kotlin is used in the backend as well and this SDK is not well suited for this usage.

As discussed in the community meeting, it would be great to rename the artifact `android-sdk`.
We don't want to rename the repository since we may have a kotlin server SDK in the future.

**Comment by nicklasl** [comment]
Taking a look at this right now and thinking about what to do about the versioning...
Since we're not at 1.0 yet I don't think we need to bump major. But what about going to `0.2.0` with this change?

**Comment by thomaspoignant** [comment]
I agree that it could be part of a `0.2.0`.

**Comment by beeme1mr** [comment]
Yes, a sub-1v can be a minor change. That's how [Release Please is configured](https://github.com/open-feature/kotlin-sdk/blob/main/release-please-config.json#L7) anyway. You can just add a `!` to the PR title to mark it a breaking. That will take care of bumping the version and making this change more visible in the release notes.
